In [1]:
import numpy as np 

In [2]:
a1 = np.array([2,1,3,4])
print(a1)

[2 1 3 4]


In [4]:
a2 = np.array([[1,2,1],[2,1,2],[1,2,3]])
print(a2)
#2-dimensional arrary

[[1 2 1]
 [2 1 2]
 [1 2 3]]


In [16]:
a3 = np.array([[[[1,1,1],[1,1,1],[2,2,2], [3,3,3], [3,3,3]]]])
print(a3)

[[[[1 1 1]
   [1 1 1]
   [2 2 2]
   [3 3 3]
   [3 3 3]]]]


In [6]:
a4 = np.arange(10,50,10)
print(a4)

[10 20 30 40]


In [7]:
a6 = np.arange(10,20)
print(a6)

[10 11 12 13 14 15 16 17 18 19]


In [8]:
a7 = np.arange(0.3,2,0.2)
print(a7)

[0.3 0.5 0.7 0.9 1.1 1.3 1.5 1.7 1.9]


In [9]:
a8 = np.linspace(3,8,9)
print(a8)

[3.    3.625 4.25  4.875 5.5   6.125 6.75  7.375 8.   ]


In [13]:
e1 = np.eye((10))
print(e1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [14]:
r1 = np.random.random((5,5))
print(r1)

[[0.11511777 0.60634176 0.51676566 0.03789339 0.34923526]
 [0.92078911 0.27784217 0.07599148 0.10440357 0.6978685 ]
 [0.28887878 0.07399418 0.05157088 0.03407074 0.95697709]
 [0.12253655 0.73843639 0.4146133  0.10004941 0.8703266 ]
 [0.93436488 0.78026185 0.90547685 0.37077006 0.16882898]]


In [17]:
print(a3.ndim) #ndim 

4


In [18]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [20]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [22]:
print(x2.size)

12


In [31]:
print(a3)

[[[[1 1 1]
   [1 1 1]
   [2 2 2]
   [3 3 3]
   [3 3 3]]]]


In [34]:
try:
    print(a3.reshape(3,6))
except Exception as e:
    print(e)
    

cannot reshape array of size 15 into shape (3,6)


In [37]:
a3.resize(3,2,3)
print(a3[0,:,:])
print(a3[0,...])


[[1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]


In [38]:
print(a3[1:9])

[[[2 2 2]
  [3 3 3]]

 [[3 3 3]
  [0 0 0]]]


In [44]:
#logical value with range 
c1 = np.arange(15)
b1 = c1 > 9
print(c1)
print(b1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[False False False False False False False False False False  True  True
  True  True  True]


In [46]:
df = np.linspace(0,6.28,20)
print(np.sin(df))

print(np.cos(df))

[ 0.          0.3245409   0.61394808  0.83689129  0.96923543  0.99665336
  0.91617692  0.73651822  0.4771265   0.16608265 -0.16294075 -0.47432472
 -0.73435989 -0.91489569 -0.99638793 -0.97001453 -0.83863058 -0.61645927
 -0.32755214 -0.0031853 ]
[ 1.          0.94587166  0.78934641  0.54736914  0.2461355  -0.08174394
 -0.40077406 -0.67641771 -0.87883463 -0.98611184 -0.98663586 -0.88034996
 -0.67876031 -0.40369032 -0.08491817  0.24304695  0.54470061  0.78738679
  0.9448331   0.99999493]


In [49]:
h = np.arange(25).reshape(5,5)
print(h > 11)

[[False False False False False]
 [False False False False False]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [50]:
j = np.array([[1,1],[2,2],[3,3]])
k = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(j.dot(k))

[[ 2  4  6  8 10]
 [ 4  8 12 16 20]
 [ 6 12 18 24 30]]


In [51]:
import pdb